services:
  postgres:
    image: postgres:16
    container_name: graphql_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
